name: Trigger auto deployment for foam-cortex-browserless

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/foam-cortex-browserless-AutoDeployTrigger-c3a0d558-4009-41d9-a965-285a138e93bb.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FOAMCORTEXBROWSERLESS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FOAMCORTEXBROWSERLESS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FOAMCORTEXBROWSERLESS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.FOAMCORTEXBROWSERLESS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FOAMCORTEXBROWSERLESS_REGISTRY_PASSWORD }}
          containerAppName: foam-cortex-browserless
          resourceGroup: foam-cortex
          imageToBuild: ghcr.io/foam-cortex-browserless:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


